# Generated by Django 4.2.3 on 2023-07-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
